name: Deployment

# on commit push, run job
on: [push]

jobs:
  run:
    # worker runs on latest ubuntu
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # checkout to our repository so we have access to the source code
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/859177010724/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'my-service-account@sal9000-307923.iam.gserviceaccount.com'

    # the actual deployment to google https://github.com/marketplace/actions/cloud-functions-deploy or https://github.com/google-github-actions/deploy-cloud-functions
    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v1.0.1'
      with:
        name: handleEvent
        description: SAL9001 deployment # nullable
        project_id: sal9000-307923
        region: us-west2
        source_dir: ./
        # name of our function in our main.py file, defaults to the resource name suffix 
        entry_point: handleEvent
        # runtime to use for the function
        runtime: python310
        # the function execution timeout
        timeout: 60
        # the maximum number of instances for the function.
        #max_instances: 1
        # optional configs, see google-cloud-actions/deploy-cloud-functions for full reference
        # list of key-value pairs to set as environment variables in the form KEY1=VALUE1,KEY2=VALUE2.

    # https://github.com/slackapi/slack-github-action
    - name: Send GitHub Action trigger data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
